=== VictorMari/pokemon-swagger-api/api/schema/characteristic.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"descriptions": {"type": "array", "items": {"type": "object", "properties": {"description": {"type": "string"}, "language": {"type": "object", "properties": {"name": {"type": "string"}, "url": {"type": "string"}}, "required": ["name", "url"]}}, "required": ["description", "language"]}}, "gene_modulo": {"type": "integer"}, "highest_stat": {"type": "object", "properties": {"name": {"type": "string"}, "url": {"type": "string"}}, "required": ["name", "url"]}, "id": {"type": "integer"}, "possible_values": {"type": "array", "items": {"type": "integer"}}}, "required": ["descriptions", "gene_modulo", "highest_stat", "id", "possible_values"]}

=== VictorMari/pokemon-swagger-api/collections/characteristics/resource_8.json
{
    "descriptions": [
        {
            "description": "Aime se d\u00e9mener",
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            }
        },
        {
            "description": "Le gusta revolverse",
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            }
        },
        {
            "description": "Likes to thrash about",
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            }
        }
    ],
    "gene_modulo": 1,
    "highest_stat": {
        "name": "attack",
        "url": "https://pokeapi.co/api/v2/stat/2/"
    },
    "id": 8,
    "possible_values": [
        1,
        6,
        11,
        16,
        21,
        26,
        31
    ]
}

=== VictorMari/pokemon-swagger-api/collections/characteristics/resource_12.json
{
    "descriptions": [
        {
            "description": "Attentif aux sons",
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            }
        },
        {
            "description": "Siempre tiene el o\u00eddo alerta",
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            }
        },
        {
            "description": "Alert to sounds",
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            }
        }
    ],
    "gene_modulo": 1,
    "highest_stat": {
        "name": "speed",
        "url": "https://pokeapi.co/api/v2/stat/6/"
    },
    "id": 12,
    "possible_values": [
        1,
        6,
        11,
        16,
        21,
        26,
        31
    ]
}
