=== VictorMari/pokemon-swagger-api/api/schema/forms.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "form_name": {
      "type": "string"
    },
    "form_names": {
      "type": "array"
    },
    "form_order": {
      "type": "integer"
    },
    "id": {
      "type": "integer"
    },
    "is_battle_only": {
      "type": "boolean"
    },
    "is_default": {
      "type": "boolean"
    },
    "is_mega": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    },
    "names": {
      "type": "array"
    },
    "order": {
      "type": "integer"
    },
    "pokemon": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "url"
      ]
    },
    "sprites": {
      "type": "object",
      "properties": {
        "back_default": {
          "type": "string"
        },
        "back_female": {
          "type": "null"
        },
        "back_shiny": {
          "type": "string"
        },
        "back_shiny_female": {
          "type": "null"
        },
        "front_default": {
          "type": "string"
        },
        "front_female": {
          "type": "null"
        },
        "front_shiny": {
          "type": "string"
        },
        "front_shiny_female": {
          "type": "null"
        }
      },
      "required": [
        "back_default",
        "back_female",
        "back_shiny",
        "back_shiny_female",
        "front_default",
        "front_female",
        "front_shiny",
        "front_shiny_female"
      ]
    },
    "types": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "slot": {
            "type": "integer"
          },
          "type": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "url"
            ]
          }
        },
        "required": [
          "slot",
          "type"
        ]
      }
    },
    "version_group": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "url"
      ]
    }
  },
  "required": [
    "form_name",
    "form_names",
    "form_order",
    "id",
    "is_battle_only",
    "is_default",
    "is_mega",
    "name",
    "names",
    "order",
    "pokemon",
    "sprites",
    "types",
    "version_group"
  ]
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_554.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 554,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "darumaka",
    "names": [],
    "order": 706,
    "pokemon": {
        "name": "darumaka",
        "url": "https://pokeapi.co/api/v2/pokemon/554/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/554.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/554.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/554.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/554.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "fire",
                "url": "https://pokeapi.co/api/v2/type/10/"
            }
        }
    ],
    "version_group": {
        "name": "black-white",
        "url": "https://pokeapi.co/api/v2/version-group/11/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_10036.json
{
    "form_name": "sandy",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\u3059\u306a\u3061\u306e\u30df\u30ce"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "\ubaa8\ub798\ub545\ub3c4\ub871"
        },
        {
            "language": {
                "name": "zh-Hant",
                "url": "https://pokeapi.co/api/v2/language/4/"
            },
            "name": "\u7802\u571f\u84d1\u8863"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Cape Sable"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "Sandumhang"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Tronco Arena"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Manto Sabbia"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Sandy Cloak"
        },
        {
            "language": {
                "name": "ja",
                "url": "https://pokeapi.co/api/v2/language/11/"
            },
            "name": "\u3059\u306a\u3061\u306e\u30df\u30ce"
        },
        {
            "language": {
                "name": "zh-Hans",
                "url": "https://pokeapi.co/api/v2/language/12/"
            },
            "name": "\u7802\u571f\u84d1\u8863"
        }
    ],
    "form_order": 2,
    "id": 10036,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "wormadam-sandy",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Cheniselle Sable"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Sandy Wormadam"
        }
    ],
    "order": 555,
    "pokemon": {
        "name": "wormadam-sandy",
        "url": "https://pokeapi.co/api/v2/pokemon/10004/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/413-sandy.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/413-sandy.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10004.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/413-sandy.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "bug",
                "url": "https://pokeapi.co/api/v2/type/7/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "ground",
                "url": "https://pokeapi.co/api/v2/type/5/"
            }
        }
    ],
    "version_group": {
        "name": "diamond-pearl",
        "url": "https://pokeapi.co/api/v2/version-group/8/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_10029.json
{
    "form_name": "rainy",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\u3042\u307e\u307f\u305a\u306e\u3059\u304c\u305f"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "\ube57\ubc29\uc6b8\uc758 \ubaa8\uc2b5"
        },
        {
            "language": {
                "name": "zh-Hant",
                "url": "https://pokeapi.co/api/v2/language/4/"
            },
            "name": "\u96e8\u6c34\u7684\u6a23\u5b50"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Forme Eau de Pluie"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "Regenform"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Forma Lluvia"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Forma Pioggia"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Rainy Form"
        },
        {
            "language": {
                "name": "ja",
                "url": "https://pokeapi.co/api/v2/language/11/"
            },
            "name": "\u3042\u307e\u307f\u305a\u306e\u3059\u304c\u305f"
        },
        {
            "language": {
                "name": "zh-Hans",
                "url": "https://pokeapi.co/api/v2/language/12/"
            },
            "name": "\u96e8\u6c34\u7684\u6837\u5b50"
        }
    ],
    "form_order": 3,
    "id": 10029,
    "is_battle_only": true,
    "is_default": true,
    "is_mega": false,
    "name": "castform-rainy",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Morph\u00e9o Eau de Pluie"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Rainy Castform"
        }
    ],
    "order": 476,
    "pokemon": {
        "name": "castform-rainy",
        "url": "https://pokeapi.co/api/v2/pokemon/10014/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/351-rainy.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10014.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10014.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10014.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "water",
                "url": "https://pokeapi.co/api/v2/type/11/"
            }
        }
    ],
    "version_group": {
        "name": "ruby-sapphire",
        "url": "https://pokeapi.co/api/v2/version-group/5/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_10222.json
{
    "form_name": "complete",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\u30d1\u30fc\u30d5\u30a7\u30af\u30c8\u30d5\u30a9\u30eb\u30e0"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "\ud37c\ud399\ud2b8\ud3fc"
        },
        {
            "language": {
                "name": "zh-Hant",
                "url": "https://pokeapi.co/api/v2/language/4/"
            },
            "name": "\u5b8c\u5168\u9ad4\u5f62\u614b"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Forme Parfaite"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "Optimumform"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Forma Completa"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Forma Perfetta"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Complete Forme"
        },
        {
            "language": {
                "name": "ja",
                "url": "https://pokeapi.co/api/v2/language/11/"
            },
            "name": "\u30d1\u30fc\u30d5\u30a7\u30af\u30c8\u30d5\u30a9\u30eb\u30e0"
        },
        {
            "language": {
                "name": "zh-Hans",
                "url": "https://pokeapi.co/api/v2/language/12/"
            },
            "name": "\u5b8c\u5168\u4f53\u5f62\u6001"
        }
    ],
    "form_order": 4,
    "id": 10222,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "zygarde-complete",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Complete Zygarde"
        }
    ],
    "order": 980,
    "pokemon": {
        "name": "zygarde-complete",
        "url": "https://pokeapi.co/api/v2/pokemon/10120/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10120.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10120.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10120.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10120.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "dragon",
                "url": "https://pokeapi.co/api/v2/type/16/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "ground",
                "url": "https://pokeapi.co/api/v2/type/5/"
            }
        }
    ],
    "version_group": {
        "name": "sun-moon",
        "url": "https://pokeapi.co/api/v2/version-group/17/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_10022.json
{
    "form_name": "w",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\uff37"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "W"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "W"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "W"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "W"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "W"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "W"
        }
    ],
    "form_order": 23,
    "id": 10022,
    "is_battle_only": false,
    "is_default": false,
    "is_mega": false,
    "name": "unown-w",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Zarbi W"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Unown W"
        }
    ],
    "order": 305,
    "pokemon": {
        "name": "unown",
        "url": "https://pokeapi.co/api/v2/pokemon/201/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/201-w.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/201-w.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/201-w.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/201-w.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "psychic",
                "url": "https://pokeapi.co/api/v2/type/14/"
            }
        }
    ],
    "version_group": {
        "name": "gold-silver",
        "url": "https://pokeapi.co/api/v2/version-group/3/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_487.json
{
    "form_name": "altered",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\u30a2\u30ca\u30b6\u30fc\u30d5\u30a9\u30eb\u30e0"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "\uc5b4\ub098\ub354\ud3fc"
        },
        {
            "language": {
                "name": "zh-Hant",
                "url": "https://pokeapi.co/api/v2/language/4/"
            },
            "name": "\u5225\u7a2e\u5f62\u614b"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Forme Alternative"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "Wandelform"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Forma Modificada"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Forma Alterata"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Altered Forme"
        },
        {
            "language": {
                "name": "ja",
                "url": "https://pokeapi.co/api/v2/language/11/"
            },
            "name": "\u30a2\u30ca\u30b6\u30fc\u30d5\u30a9\u30eb\u30e0"
        },
        {
            "language": {
                "name": "zh-Hans",
                "url": "https://pokeapi.co/api/v2/language/12/"
            },
            "name": "\u522b\u79cd\u5f62\u6001"
        }
    ],
    "form_order": 1,
    "id": 487,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "giratina-altered",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Giratina Alternative"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Altered Giratina"
        }
    ],
    "order": 617,
    "pokemon": {
        "name": "giratina-altered",
        "url": "https://pokeapi.co/api/v2/pokemon/487/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/487.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/487.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/487.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/487.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "ghost",
                "url": "https://pokeapi.co/api/v2/type/8/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "dragon",
                "url": "https://pokeapi.co/api/v2/type/16/"
            }
        }
    ],
    "version_group": {
        "name": "diamond-pearl",
        "url": "https://pokeapi.co/api/v2/version-group/8/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_230.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 230,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "kingdra",
    "names": [],
    "order": 179,
    "pokemon": {
        "name": "kingdra",
        "url": "https://pokeapi.co/api/v2/pokemon/230/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/230.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/230.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/230.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/230.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "water",
                "url": "https://pokeapi.co/api/v2/type/11/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "dragon",
                "url": "https://pokeapi.co/api/v2/type/16/"
            }
        }
    ],
    "version_group": {
        "name": "gold-silver",
        "url": "https://pokeapi.co/api/v2/version-group/3/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_645.json
{
    "form_name": "incarnate",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\u3051\u3057\u3093\u30d5\u30a9\u30eb\u30e0"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "\ud654\uc2e0\ud3fc"
        },
        {
            "language": {
                "name": "zh-Hant",
                "url": "https://pokeapi.co/api/v2/language/4/"
            },
            "name": "\u5316\u8eab\u5f62\u614b"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Forme Avatar"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "Inkarnationsform"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Forma Avatar"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Forma Incarnazione"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Incarnate Forme"
        },
        {
            "language": {
                "name": "ja",
                "url": "https://pokeapi.co/api/v2/language/11/"
            },
            "name": "\u3051\u3057\u3093\u30d5\u30a9\u30eb\u30e0"
        },
        {
            "language": {
                "name": "zh-Hans",
                "url": "https://pokeapi.co/api/v2/language/12/"
            },
            "name": "\u5316\u8eab\u5f62\u6001"
        }
    ],
    "form_order": 1,
    "id": 645,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "landorus-incarnate",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "D\u00e9m\u00e9t\u00e9ros Avatar"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Incarnate Landorus"
        }
    ],
    "order": 806,
    "pokemon": {
        "name": "landorus-incarnate",
        "url": "https://pokeapi.co/api/v2/pokemon/645/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/645.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/645.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/645.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/645.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "ground",
                "url": "https://pokeapi.co/api/v2/type/5/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "flying",
                "url": "https://pokeapi.co/api/v2/type/3/"
            }
        }
    ],
    "version_group": {
        "name": "black-white",
        "url": "https://pokeapi.co/api/v2/version-group/11/"
    }
}
