=== VictorMari/pokemon-swagger-api/api/schema/forms.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "form_name": {
      "type": "string"
    },
    "form_names": {
      "type": "array"
    },
    "form_order": {
      "type": "integer"
    },
    "id": {
      "type": "integer"
    },
    "is_battle_only": {
      "type": "boolean"
    },
    "is_default": {
      "type": "boolean"
    },
    "is_mega": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    },
    "names": {
      "type": "array"
    },
    "order": {
      "type": "integer"
    },
    "pokemon": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "url"
      ]
    },
    "sprites": {
      "type": "object",
      "properties": {
        "back_default": {
          "type": "string"
        },
        "back_female": {
          "type": "null"
        },
        "back_shiny": {
          "type": "string"
        },
        "back_shiny_female": {
          "type": "null"
        },
        "front_default": {
          "type": "string"
        },
        "front_female": {
          "type": "null"
        },
        "front_shiny": {
          "type": "string"
        },
        "front_shiny_female": {
          "type": "null"
        }
      },
      "required": [
        "back_default",
        "back_female",
        "back_shiny",
        "back_shiny_female",
        "front_default",
        "front_female",
        "front_shiny",
        "front_shiny_female"
      ]
    },
    "types": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "slot": {
            "type": "integer"
          },
          "type": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "url"
            ]
          }
        },
        "required": [
          "slot",
          "type"
        ]
      }
    },
    "version_group": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "url"
      ]
    }
  },
  "required": [
    "form_name",
    "form_names",
    "form_order",
    "id",
    "is_battle_only",
    "is_default",
    "is_mega",
    "name",
    "names",
    "order",
    "pokemon",
    "sprites",
    "types",
    "version_group"
  ]
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_10034.json
{
    "form_name": "sandy",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\u3059\u306a\u3061\u306e\u30df\u30ce"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "\ubaa8\ub798\ub545\ub3c4\ub871"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Cape Sable"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "Sandumhang"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Tronco Arena"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Manto Sabbia"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Sandy Cloak"
        }
    ],
    "form_order": 2,
    "id": 10034,
    "is_battle_only": false,
    "is_default": false,
    "is_mega": false,
    "name": "burmy-sandy",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Cheniti Sable"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Sandy Burmy"
        }
    ],
    "order": 552,
    "pokemon": {
        "name": "burmy",
        "url": "https://pokeapi.co/api/v2/pokemon/412/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/412-sandy.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/412-sandy.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/412-sandy.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/412-sandy.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "bug",
                "url": "https://pokeapi.co/api/v2/type/7/"
            }
        }
    ],
    "version_group": {
        "name": "diamond-pearl",
        "url": "https://pokeapi.co/api/v2/version-group/8/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_412.json
{
    "form_name": "plant",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\u304f\u3055\u304d\u306e\u30df\u30ce"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "\ucd08\ubaa9\ub3c4\ub871"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Cape Plante"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "Pflanzenumhang"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Tronco Planta"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Manto Pianta"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Plant Cloak"
        }
    ],
    "form_order": 1,
    "id": 412,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "burmy-plant",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Cheniti Plante"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Plant Burmy"
        }
    ],
    "order": 551,
    "pokemon": {
        "name": "burmy",
        "url": "https://pokeapi.co/api/v2/pokemon/412/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/412.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/412.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/412.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/412.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "bug",
                "url": "https://pokeapi.co/api/v2/type/7/"
            }
        }
    ],
    "version_group": {
        "name": "diamond-pearl",
        "url": "https://pokeapi.co/api/v2/version-group/8/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_783.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 783,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "hakamo-o",
    "names": [],
    "order": 1094,
    "pokemon": {
        "name": "hakamo-o",
        "url": "https://pokeapi.co/api/v2/pokemon/783/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/783.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/783.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/783.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/783.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "dragon",
                "url": "https://pokeapi.co/api/v2/type/16/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "fighting",
                "url": "https://pokeapi.co/api/v2/type/2/"
            }
        }
    ],
    "version_group": {
        "name": "sun-moon",
        "url": "https://pokeapi.co/api/v2/version-group/17/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_10067.json
{
    "form_name": "zen",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\u30c0\u30eb\u30de\u30e2\u30fc\u30c9"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "\ub2ec\ub9c8\ubaa8\ub4dc"
        },
        {
            "language": {
                "name": "zh-Hant",
                "url": "https://pokeapi.co/api/v2/language/4/"
            },
            "name": "\u9054\u6469\u6a21\u5f0f"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Mode Transe"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "Trance-Modus"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Modo Daruma"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Stato Zen"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Zen Mode"
        },
        {
            "language": {
                "name": "ja",
                "url": "https://pokeapi.co/api/v2/language/11/"
            },
            "name": "\u30c0\u30eb\u30de\u30e2\u30fc\u30c9"
        },
        {
            "language": {
                "name": "zh-Hans",
                "url": "https://pokeapi.co/api/v2/language/12/"
            },
            "name": "\u8fbe\u6469\u6a21\u5f0f"
        }
    ],
    "form_order": 2,
    "id": 10067,
    "is_battle_only": true,
    "is_default": true,
    "is_mega": false,
    "name": "darmanitan-zen",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Darumacho Transe"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Zen Darmanitan"
        }
    ],
    "order": 708,
    "pokemon": {
        "name": "darmanitan-zen",
        "url": "https://pokeapi.co/api/v2/pokemon/10017/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/555-zen.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/555-zen.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10017.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/555-zen.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "fire",
                "url": "https://pokeapi.co/api/v2/type/10/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "psychic",
                "url": "https://pokeapi.co/api/v2/type/14/"
            }
        }
    ],
    "version_group": {
        "name": "black-white",
        "url": "https://pokeapi.co/api/v2/version-group/11/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_10220.json
{
    "form_name": "10",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\uff11\uff10\uff05\u30d5\u30a9\u30eb\u30e0"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "10%\ud3fc"
        },
        {
            "language": {
                "name": "zh-Hant",
                "url": "https://pokeapi.co/api/v2/language/4/"
            },
            "name": "\uff11\uff10\uff05\u5f62\u614b"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Forme 10 %"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "10%-Form"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Forma 10%"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Forma 10%"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "10% Forme"
        },
        {
            "language": {
                "name": "ja",
                "url": "https://pokeapi.co/api/v2/language/11/"
            },
            "name": "\uff11\uff10\uff05\u30d5\u30a9\u30eb\u30e0"
        },
        {
            "language": {
                "name": "zh-Hans",
                "url": "https://pokeapi.co/api/v2/language/12/"
            },
            "name": "\uff11\uff10\uff05\u5f62\u6001"
        }
    ],
    "form_order": 2,
    "id": 10220,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "zygarde-10",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "10% Zygarde"
        }
    ],
    "order": 978,
    "pokemon": {
        "name": "zygarde-10",
        "url": "https://pokeapi.co/api/v2/pokemon/10118/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10118.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10118.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10118.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10118.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "dragon",
                "url": "https://pokeapi.co/api/v2/type/16/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "ground",
                "url": "https://pokeapi.co/api/v2/type/5/"
            }
        }
    ],
    "version_group": {
        "name": "sun-moon",
        "url": "https://pokeapi.co/api/v2/version-group/17/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_10228.json
{
    "form_name": "midnight",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\u307e\u3088\u306a\u304b\u306e\u3059\u304c\u305f"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "\ud55c\ubc24\uc911\uc758 \ubaa8\uc2b5"
        },
        {
            "language": {
                "name": "zh-Hant",
                "url": "https://pokeapi.co/api/v2/language/4/"
            },
            "name": "\u9ed1\u591c\u7684\u6a23\u5b50"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Forme Nocturne"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "Nachtform"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Forma Nocturna"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "Forma Notte"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Midnight Form"
        },
        {
            "language": {
                "name": "ja",
                "url": "https://pokeapi.co/api/v2/language/11/"
            },
            "name": "\u307e\u3088\u306a\u304b\u306e\u3059\u304c\u305f"
        },
        {
            "language": {
                "name": "zh-Hans",
                "url": "https://pokeapi.co/api/v2/language/12/"
            },
            "name": "\u9ed1\u591c\u7684\u6837\u5b50"
        }
    ],
    "form_order": 2,
    "id": 10228,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "lycanroc-midnight",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Midnight Lycanroc"
        }
    ],
    "order": 1017,
    "pokemon": {
        "name": "lycanroc-midnight",
        "url": "https://pokeapi.co/api/v2/pokemon/10126/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10126.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10126.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10126.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10126.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "rock",
                "url": "https://pokeapi.co/api/v2/type/6/"
            }
        }
    ],
    "version_group": {
        "name": "sun-moon",
        "url": "https://pokeapi.co/api/v2/version-group/17/"
    }
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-forms/resource_10021.json
{
    "form_name": "v",
    "form_names": [
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "https://pokeapi.co/api/v2/language/1/"
            },
            "name": "\uff36"
        },
        {
            "language": {
                "name": "ko",
                "url": "https://pokeapi.co/api/v2/language/3/"
            },
            "name": "V"
        },
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "V"
        },
        {
            "language": {
                "name": "de",
                "url": "https://pokeapi.co/api/v2/language/6/"
            },
            "name": "V"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "V"
        },
        {
            "language": {
                "name": "it",
                "url": "https://pokeapi.co/api/v2/language/8/"
            },
            "name": "V"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "V"
        }
    ],
    "form_order": 22,
    "id": 10021,
    "is_battle_only": false,
    "is_default": false,
    "is_mega": false,
    "name": "unown-v",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Zarbi V"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Unown V"
        }
    ],
    "order": 304,
    "pokemon": {
        "name": "unown",
        "url": "https://pokeapi.co/api/v2/pokemon/201/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/201-v.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/201-v.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/201-v.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/201-v.png",
        "front_shiny_female": null
    },
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "psychic",
                "url": "https://pokeapi.co/api/v2/type/14/"
            }
        }
    ],
    "version_group": {
        "name": "gold-silver",
        "url": "https://pokeapi.co/api/v2/version-group/3/"
    }
}
