=== VictorMari/pokemon-swagger-api/api/schema/pokeathlonstats.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "affecting_natures": {
      "type": "object",
      "properties": {
        "decrease": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "max_change": {
                "type": "integer"
              },
              "nature": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "url"
                ]
              }
            },
            "required": [
              "max_change",
              "nature"
            ]
          }
        },
        "increase": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "max_change": {
                "type": "integer"
              },
              "nature": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "url"
                ]
              }
            },
            "required": [
              "max_change",
              "nature"
            ]
          }
        }
      },
      "required": [
        "decrease",
        "increase"
      ]
    },
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "names": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "url"
            ]
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "language",
          "name"
        ]
      }
    }
  },
  "required": [
    "affecting_natures",
    "id",
    "name",
    "names"
  ]
}

=== VictorMari/pokemon-swagger-api/collections/pokeathlon-stats/resource_4.json
{
    "affecting_natures": {
        "decrease": [],
        "increase": []
    },
    "id": 4,
    "name": "stamina",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Endurance"
        },
        {
            "language": {
                "name": "es",
                "url": "https://pokeapi.co/api/v2/language/7/"
            },
            "name": "Firmeza"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Stamina"
        }
    ]
}
