=== VictorMari/pokemon-swagger-api/api/schema/shapes.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "awesome_names": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "awesome_name": {
            "type": "string"
          },
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "url"
            ]
          }
        },
        "required": [
          "awesome_name",
          "language"
        ]
      }
    },
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "names": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "language": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "url"
            ]
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "language",
          "name"
        ]
      }
    },
    "pokemon_species": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "url"
        ]
      }
    }
  },
  "required": [
    "awesome_names",
    "id",
    "name",
    "names",
    "pokemon_species"
  ]
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-shapes/resource_10.json
{
    "awesome_names": [
        {
            "awesome_name": "Ciliaire",
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            }
        },
        {
            "awesome_name": "Cilial",
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            }
        }
    ],
    "id": 10,
    "name": "tentacles",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Tentacules"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Tentacles"
        }
    ],
    "pokemon_species": [
        {
            "name": "tentacool",
            "url": "https://pokeapi.co/api/v2/pokemon-species/72/"
        },
        {
            "name": "tentacruel",
            "url": "https://pokeapi.co/api/v2/pokemon-species/73/"
        },
        {
            "name": "omanyte",
            "url": "https://pokeapi.co/api/v2/pokemon-species/138/"
        },
        {
            "name": "omastar",
            "url": "https://pokeapi.co/api/v2/pokemon-species/139/"
        },
        {
            "name": "octillery",
            "url": "https://pokeapi.co/api/v2/pokemon-species/224/"
        },
        {
            "name": "carnivine",
            "url": "https://pokeapi.co/api/v2/pokemon-species/455/"
        },
        {
            "name": "giratina",
            "url": "https://pokeapi.co/api/v2/pokemon-species/487/"
        },
        {
            "name": "boldore",
            "url": "https://pokeapi.co/api/v2/pokemon-species/525/"
        },
        {
            "name": "gigalith",
            "url": "https://pokeapi.co/api/v2/pokemon-species/526/"
        },
        {
            "name": "frillish",
            "url": "https://pokeapi.co/api/v2/pokemon-species/592/"
        },
        {
            "name": "jellicent",
            "url": "https://pokeapi.co/api/v2/pokemon-species/593/"
        },
        {
            "name": "ferrothorn",
            "url": "https://pokeapi.co/api/v2/pokemon-species/598/"
        },
        {
            "name": "inkay",
            "url": "https://pokeapi.co/api/v2/pokemon-species/686/"
        },
        {
            "name": "trevenant",
            "url": "https://pokeapi.co/api/v2/pokemon-species/709/"
        },
        {
            "name": "toxapex",
            "url": "https://pokeapi.co/api/v2/pokemon-species/748/"
        },
        {
            "name": "wimpod",
            "url": "https://pokeapi.co/api/v2/pokemon-species/767/"
        },
        {
            "name": "nihilego",
            "url": "https://pokeapi.co/api/v2/pokemon-species/793/"
        },
        {
            "name": "buzzwole",
            "url": "https://pokeapi.co/api/v2/pokemon-species/794/"
        },
        {
            "name": "sizzlipede",
            "url": "https://pokeapi.co/api/v2/pokemon-species/850/"
        },
        {
            "name": "clobbopus",
            "url": "https://pokeapi.co/api/v2/pokemon-species/852/"
        },
        {
            "name": "pincurchin",
            "url": "https://pokeapi.co/api/v2/pokemon-species/871/"
        },
        {
            "name": "centiskorch",
            "url": "https://pokeapi.co/api/v2/pokemon-species/851/"
        },
        {
            "name": "grapploct",
            "url": "https://pokeapi.co/api/v2/pokemon-species/853/"
        }
    ]
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-shapes/resource_13.json
{
    "awesome_names": [
        {
            "awesome_name": "L\u00e9pidopt\u00e8re",
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            }
        },
        {
            "awesome_name": "Lepidopterous",
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            }
        }
    ],
    "id": 13,
    "name": "bug-wings",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Ailes d'insecte"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Bug wings"
        }
    ],
    "pokemon_species": [
        {
            "name": "butterfree",
            "url": "https://pokeapi.co/api/v2/pokemon-species/12/"
        },
        {
            "name": "beedrill",
            "url": "https://pokeapi.co/api/v2/pokemon-species/15/"
        },
        {
            "name": "venomoth",
            "url": "https://pokeapi.co/api/v2/pokemon-species/49/"
        },
        {
            "name": "scyther",
            "url": "https://pokeapi.co/api/v2/pokemon-species/123/"
        },
        {
            "name": "yanma",
            "url": "https://pokeapi.co/api/v2/pokemon-species/193/"
        },
        {
            "name": "crobat",
            "url": "https://pokeapi.co/api/v2/pokemon-species/169/"
        },
        {
            "name": "scizor",
            "url": "https://pokeapi.co/api/v2/pokemon-species/212/"
        },
        {
            "name": "beautifly",
            "url": "https://pokeapi.co/api/v2/pokemon-species/267/"
        },
        {
            "name": "dustox",
            "url": "https://pokeapi.co/api/v2/pokemon-species/269/"
        },
        {
            "name": "masquerain",
            "url": "https://pokeapi.co/api/v2/pokemon-species/284/"
        },
        {
            "name": "ninjask",
            "url": "https://pokeapi.co/api/v2/pokemon-species/291/"
        },
        {
            "name": "vibrava",
            "url": "https://pokeapi.co/api/v2/pokemon-species/329/"
        },
        {
            "name": "kricketune",
            "url": "https://pokeapi.co/api/v2/pokemon-species/402/"
        },
        {
            "name": "mothim",
            "url": "https://pokeapi.co/api/v2/pokemon-species/414/"
        },
        {
            "name": "vespiquen",
            "url": "https://pokeapi.co/api/v2/pokemon-species/416/"
        },
        {
            "name": "yanmega",
            "url": "https://pokeapi.co/api/v2/pokemon-species/469/"
        },
        {
            "name": "volcarona",
            "url": "https://pokeapi.co/api/v2/pokemon-species/637/"
        },
        {
            "name": "ribombee",
            "url": "https://pokeapi.co/api/v2/pokemon-species/743/"
        },
        {
            "name": "vivillon",
            "url": "https://pokeapi.co/api/v2/pokemon-species/666/"
        },
        {
            "name": "frosmoth",
            "url": "https://pokeapi.co/api/v2/pokemon-species/873/"
        }
    ]
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-shapes/resource_7.json
{
    "awesome_names": [
        {
            "awesome_name": "Crural",
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            }
        },
        {
            "awesome_name": "Crural",
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            }
        }
    ],
    "id": 7,
    "name": "legs",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Jambes"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Legs"
        }
    ],
    "pokemon_species": [
        {
            "name": "oddish",
            "url": "https://pokeapi.co/api/v2/pokemon-species/43/"
        },
        {
            "name": "poliwag",
            "url": "https://pokeapi.co/api/v2/pokemon-species/60/"
        },
        {
            "name": "doduo",
            "url": "https://pokeapi.co/api/v2/pokemon-species/84/"
        },
        {
            "name": "tangela",
            "url": "https://pokeapi.co/api/v2/pokemon-species/114/"
        },
        {
            "name": "porygon",
            "url": "https://pokeapi.co/api/v2/pokemon-species/137/"
        },
        {
            "name": "dodrio",
            "url": "https://pokeapi.co/api/v2/pokemon-species/85/"
        },
        {
            "name": "exeggutor",
            "url": "https://pokeapi.co/api/v2/pokemon-species/103/"
        },
        {
            "name": "wooper",
            "url": "https://pokeapi.co/api/v2/pokemon-species/194/"
        },
        {
            "name": "torchic",
            "url": "https://pokeapi.co/api/v2/pokemon-species/255/"
        },
        {
            "name": "seedot",
            "url": "https://pokeapi.co/api/v2/pokemon-species/273/"
        },
        {
            "name": "shroomish",
            "url": "https://pokeapi.co/api/v2/pokemon-species/285/"
        },
        {
            "name": "azurill",
            "url": "https://pokeapi.co/api/v2/pokemon-species/298/"
        },
        {
            "name": "porygon2",
            "url": "https://pokeapi.co/api/v2/pokemon-species/233/"
        },
        {
            "name": "bonsly",
            "url": "https://pokeapi.co/api/v2/pokemon-species/438/"
        },
        {
            "name": "cherrim",
            "url": "https://pokeapi.co/api/v2/pokemon-species/421/"
        },
        {
            "name": "roggenrola",
            "url": "https://pokeapi.co/api/v2/pokemon-species/524/"
        },
        {
            "name": "swirlix",
            "url": "https://pokeapi.co/api/v2/pokemon-species/684/"
        },
        {
            "name": "dewpider",
            "url": "https://pokeapi.co/api/v2/pokemon-species/751/"
        },
        {
            "name": "bounsweet",
            "url": "https://pokeapi.co/api/v2/pokemon-species/761/"
        },
        {
            "name": "carkol",
            "url": "https://pokeapi.co/api/v2/pokemon-species/838/"
        },
        {
            "name": "hatenna",
            "url": "https://pokeapi.co/api/v2/pokemon-species/856/"
        },
        {
            "name": "stonjourner",
            "url": "https://pokeapi.co/api/v2/pokemon-species/874/"
        },
        {
            "name": "dracovish",
            "url": "https://pokeapi.co/api/v2/pokemon-species/882/"
        }
    ]
}

=== VictorMari/pokemon-swagger-api/collections/pokemon-shapes/resource_5.json
{
    "awesome_names": [
        {
            "awesome_name": "Alvin",
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            }
        },
        {
            "awesome_name": "Alvine",
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            }
        }
    ],
    "id": 5,
    "name": "blob",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "https://pokeapi.co/api/v2/language/5/"
            },
            "name": "Goutte"
        },
        {
            "language": {
                "name": "en",
                "url": "https://pokeapi.co/api/v2/language/9/"
            },
            "name": "Blob"
        }
    ],
    "pokemon_species": [
        {
            "name": "diglett",
            "url": "https://pokeapi.co/api/v2/pokemon-species/50/"
        },
        {
            "name": "weepinbell",
            "url": "https://pokeapi.co/api/v2/pokemon-species/70/"
        },
        {
            "name": "victreebel",
            "url": "https://pokeapi.co/api/v2/pokemon-species/71/"
        },
        {
            "name": "horsea",
            "url": "https://pokeapi.co/api/v2/pokemon-species/116/"
        },
        {
            "name": "staryu",
            "url": "https://pokeapi.co/api/v2/pokemon-species/120/"
        },
        {
            "name": "seadra",
            "url": "https://pokeapi.co/api/v2/pokemon-species/117/"
        },
        {
            "name": "starmie",
            "url": "https://pokeapi.co/api/v2/pokemon-species/121/"
        },
        {
            "name": "wobbuffet",
            "url": "https://pokeapi.co/api/v2/pokemon-species/202/"
        },
        {
            "name": "kingdra",
            "url": "https://pokeapi.co/api/v2/pokemon-species/230/"
        },
        {
            "name": "shedinja",
            "url": "https://pokeapi.co/api/v2/pokemon-species/292/"
        },
        {
            "name": "lileep",
            "url": "https://pokeapi.co/api/v2/pokemon-species/345/"
        },
        {
            "name": "beldum",
            "url": "https://pokeapi.co/api/v2/pokemon-species/374/"
        },
        {
            "name": "cradily",
            "url": "https://pokeapi.co/api/v2/pokemon-species/346/"
        },
        {
            "name": "burmy",
            "url": "https://pokeapi.co/api/v2/pokemon-species/412/"
        },
        {
            "name": "spiritomb",
            "url": "https://pokeapi.co/api/v2/pokemon-species/442/"
        },
        {
            "name": "wormadam",
            "url": "https://pokeapi.co/api/v2/pokemon-species/413/"
        },
        {
            "name": "petilil",
            "url": "https://pokeapi.co/api/v2/pokemon-species/548/"
        },
        {
            "name": "maractus",
            "url": "https://pokeapi.co/api/v2/pokemon-species/556/"
        },
        {
            "name": "vanillite",
            "url": "https://pokeapi.co/api/v2/pokemon-species/582/"
        },
        {
            "name": "litwick",
            "url": "https://pokeapi.co/api/v2/pokemon-species/607/"
        },
        {
            "name": "lilligant",
            "url": "https://pokeapi.co/api/v2/pokemon-species/549/"
        },
        {
            "name": "vanillish",
            "url": "https://pokeapi.co/api/v2/pokemon-species/583/"
        },
        {
            "name": "honedge",
            "url": "https://pokeapi.co/api/v2/pokemon-species/679/"
        },
        {
            "name": "spewpa",
            "url": "https://pokeapi.co/api/v2/pokemon-species/665/"
        },
        {
            "name": "aegislash",
            "url": "https://pokeapi.co/api/v2/pokemon-species/681/"
        },
        {
            "name": "skrelp",
            "url": "https://pokeapi.co/api/v2/pokemon-species/690/"
        },
        {
            "name": "mareanie",
            "url": "https://pokeapi.co/api/v2/pokemon-species/747/"
        },
        {
            "name": "morelull",
            "url": "https://pokeapi.co/api/v2/pokemon-species/755/"
        },
        {
            "name": "dragalge",
            "url": "https://pokeapi.co/api/v2/pokemon-species/691/"
        },
        {
            "name": "gourgeist",
            "url": "https://pokeapi.co/api/v2/pokemon-species/711/"
        },
        {
            "name": "dhelmise",
            "url": "https://pokeapi.co/api/v2/pokemon-species/781/"
        },
        {
            "name": "gossifleur",
            "url": "https://pokeapi.co/api/v2/pokemon-species/829/"
        },
        {
            "name": "eldegoss",
            "url": "https://pokeapi.co/api/v2/pokemon-species/830/"
        },
        {
            "name": "cofagrigus",
            "url": "https://pokeapi.co/api/v2/pokemon-species/563/"
        },
        {
            "name": "malamar",
            "url": "https://pokeapi.co/api/v2/pokemon-species/687/"
        },
        {
            "name": "runerigus",
            "url": "https://pokeapi.co/api/v2/pokemon-species/867/"
        },
        {
            "name": "alcremie",
            "url": "https://pokeapi.co/api/v2/pokemon-species/869/"
        },
        {
            "name": "hatterene",
            "url": "https://pokeapi.co/api/v2/pokemon-species/858/"
        }
    ]
}
